AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
